/**
 * Created by ZZH on 2016/4/13.
 */

// total : 动画的总帧数  delay: 每帧的间隔时间　path : 名称  FixN : 格式标示量  sindex : 从某帧开始
var AnimatesData = {
    "na_normal": {"total": 4, "delay": 0.2, "path": "na_normal_"},
    "na_run": {"total": 6, "delay": 0.01, "path": "na_run_"},
    "na_die": {"total": 6, "delay": 0.05, "path": "na_die_"},
    "na_hui": {"total": 6, "delay": 0.05, "path": "na_hui_"},

    "emy_lang": {"total": 4, "delay": 0.2, "path": "emy_lang_"},
    "emy_lang_run": {"total": 4, "delay": 0.2, "path": "emy_lang_run_"},
    "emy_zhu": {"total": 4, "delay": 0.2, "path": "emy_zhu_"},
    "emy_zhu_run": {"total": 4, "delay": 0.2, "path": "emy_zhu_run_"},
    "emy_niao": {"total": 1, "delay": 0.2, "path": "emy_niao_"},
    "emy_niao_run": {"total": 3, "delay": 0.2, "path": "emy_niao_"},
    "emy_die": {"total": 9, "delay": 0.05, "path": "emy_die_"},

    "dec_oneDoor": {"total": 1, "delay": 0.05, "path": "dec_oneDoor_"},
    "dec_oneDoor_die": {"total": 15, "delay": 0.03, "path": "dec_oneDoor_"},
    "dec_twoDoor": {"total": 1, "delay": 0.05, "path": "dec_twoDoor_"},
    "dec_twoDoor_die": {"total": 15, "delay": 0.03, "path": "dec_twoDoor_"},
    "dec_oneBox": {"total": 1, "delay": 0.05, "path": "dec_oneBox_"},
    "dec_oneBox_die": {"total": 11, "delay": 0.03, "path": "dec_oneBox_"},
    "dec_twoBox": {"total": 1, "delay": 0.05, "path": "dec_twoBox_"},
    "dec_twoBox_die": {"total": 11, "delay": 0.03, "path": "dec_twoBox_"},
    "dec_godeng": {"total": 1, "delay": 0.05, "path": "dec_godeng_"},
    "dec_godeng_die": {"total": 12, "delay": 0.03, "path": "dec_godeng_"},
    "dec_badeng": {"total": 1, "delay": 0.05, "path": "dec_badeng_"},
    "dec_badeng_die": {"total": 11, "delay": 0.03, "path": "dec_badeng_"},
    "dec_tong": {"total": 1, "delay": 0.05, "path": "dec_tong_"},
    "dec_tong_die": {"total": 12, "delay": 0.03, "path": "dec_tong_"},
    "dec_yuantong": {"total": 1, "delay": 0.05, "path": "dec_yuantong_"},
    "dec_yuantong_die": {"total": 15, "delay": 0.03, "path": "dec_yuantong_"},
    "dec_tie": {"total": 1, "delay": 0.05, "path": "dec_tie_"},
    "dec_tie_die": {"total": 16, "delay": 0.03, "path": "dec_tie_"},
    "dec_book": {"total": 1, "delay": 0.05, "path": "shugui-800", "FixN": 2},
    "dec_book_die": {"total": 19, "delay": 0.03, "path": "shugui-800", "FixN": 2, "sindex": 2},
    "dec_tv": {"total": 1, "delay": 0.05, "path": "tv-600", "FixN": 2},
    "dec_tv_die": {"total": 26, "delay": 0.03, "path": "tv-600", "FixN": 2, "sindex": 2},
    "dec_pic": {"total": 1, "delay": 0.05, "path": "huaxiang_100", "FixN": 2},
    "dec_pic_die": {"total": 19, "delay": 0.03, "path": "huaxiang_100", "FixN": 2, "sindex": 2},
    "dec_shiyan": {"total": 1, "delay": 0.05, "path": "shiyantai-700", "FixN": 2},
    "dec_shiyan_die": {"total": 11, "delay": 0.03, "path": "shiyantai-700", "FixN": 2, "sindex": 2},

    "naf": {"total": 6, "delay": 0.005},
    "bhp": {"total": 5, "delay": 0.2, "path": "niu_"},
    "bt": {"total": 4, "delay": 0.2, "path": "bt_"},
    "nag": {"total": 1, "delay": 0.2, "path": "nag_"},
    "nag_die": {"total": 7, "delay": 0.1, "path": "nag_die_"},
    "nl": {"total": 1, "delay": 0.2, "path": "nail_"},
    "nlt": {"total": 1, "delay": 0.2, "path": "nlt_"},
    "tnl": {"total": 1, "delay": 0.2, "path": "nailTwo_"},
    "fnl": {"total": 1, "delay": 0.2, "path": "nailSi_"},
    "pt": {"total": 2, "delay": 0.2, "path": "pt_"},
    "jz": {"total": 1, "delay": 0.2, "path": "jz_", "sindex": 100},
    "jz_die": {"total": 48, "delay": 0.05, "path": "jz_"},
    "wl": {"total": 1, "delay": 0.2, "path": "wall_"},
    "wl_die": {"total": 8, "delay": 0.05, "path": "wall_die_"},
    "ntn": {"total": 2, "delay": 0.1, "path": "ntn_"},
    "ntn_die": {"total": 7, "delay": 0.05, "path": "ntn_die_"},
    "boss_die": {"total": 104, "delay": 0.03, "path": "shaboos-20", "FixN": 3},
    "na_tc": {"total": 25, "delay": 0.03, "path": "tanchuangrenzhedonghua-500", "FixN": 2},

    "help_1": {"total": 4, "delay": 0.2, "path": "emy_lang_"},
    "help_2": {"total": 18, "delay": 0.03, "path": "2-100", "FixN": 2},
    "help_4": {"total": 43, "delay": 0.03, "path": "shitou-8000100", "FixN": 2},
    "help_5": {"total": 34, "delay": 0.05, "path": "niu-300", "FixN": 2},
    "help_9": {"total": 15, "delay": 0.05, "path": "lubiao-400", "FixN": 2},
    "help_10": {"total": 19, "delay": 0.05, "path": "lanseyang-500", "FixN": 2},
    "help_11": {"total": 28, "delay": 0.03, "path": "fensheng-600", "FixN": 2},
    "help_12": {"total": 15, "delay": 0.05, "path": "kaiguan-700", "FixN": 2},
    "help_13": {"total": 4, "delay": 0.2, "path": "emy_lang_"},
    "help_14": {"total": 4, "delay": 0.2, "path": "emy_lang_"},
    "help_15": {"total": 4, "delay": 0.2, "path": "emy_lang_"}


}